# Created by Andryev Lemes
version: '3.2'
services:
  postgres_beblue:
    build:
      context: ./src/main/docker/postgres
    ports:
      - 5432:5432
    container_name: postgres_beblue
    networks:
      - backend
  beblue-api:
    build:
      context: ./target
      dockerfile: ../src/main/docker/beblue-api/Dockerfile
    ports:
      - 8080:8080
    container_name: beblue-api
    environment:
      - POSTGRES_URL=postgres_beblue
      - POSTGRES_USER=beblue
      - POSTGRES_PASSWORD=bebluepass
      - POSTGRES_DATABASE=beblue
    depends_on:
      - postgres_beblue
    networks:
      - backend
networks:
  backend:
    driver: "bridge"

