version: '1.0'
services:
  postgres:
    build:
      context: postgres
    ports:
      - 5432:5432
    container_name: postgres
    volumes:
      - /opt/postgres_home:/var/lib/postgresql/data:z
    networks:
      - backend
  beblue-api:
    build:
      context:
    ports:
      - 8080:8080
    container_name: beblue-api
    volumes:
      - /opt/beblue:/var/beblue_home:z
    environment:
      - POSTGRES_URL=postgres
      - POSTGRES_USER=beblue
      - POSTGRES_PASSWORD=bebluepass
      - POSTGRES_DATABASE=beblue
    depends_on:
      - postgres
    networks:
      - backend
networks:
  backend:
    driver: "bridge"

